version: '3'
services:

#Gestion operation service------------------------------


  dbGestionOperation:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "go_service_db" # Set the name of your database
    #   MYSQL_USER: "root"         # Set your MySQL username
    #   MYSQL_PASSWORD: "" # Set your MySQL password
    volumes:
      - dbGestionOperation_data:/var/lib/mysql
    networks:
      - app-network

  go: # meaning the name of the app
    depends_on:
      - dbGestionOperation
    build: . # Specify the path to your Spring Boot application Dockerfile
    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://dbGestionOperation:3306/go_service_db" # Database URL
      #SPRING_DATASOURCE_USERNAME: "myuser"                       # Database username
      #SPRING_DATASOURCE_PASSWORD: "mypassword"                   # Database password
    ports:
      - '8082:8080'
    networks:
      - app-network





networks:
  app-network:
    external: true

volumes:
  dbGestionOperation_data:
